# This file was generated by PygramETL-DeclarativeETL (https://github.com/smath17/declarative-etl)

import psycopg2
import pygrametl
from pygrametl.datasources import SQLSource, CSVSource
from pygrametl.tables import CachedDimension, FactTable

# Open connection to the data warehouse.
# CHANGE CONNECTION VALUES TO MATCH YOUR CREDENTIALS
dw_string = "host='localhost' dbname='test' user='postgres' password='1234'"
dw_conn = psycopg2.connect(dw_string)
# ConnectionWrapper shares the connection between all relevant PygramETL abstractions
# allowing dimensions and fact to connect to their respective tables
dw_conn_wrapper = pygrametl.ConnectionWrapper(connection=dw_conn)

Customer_Dimension = CachedDimension(
    name='Customer_Dimension',
    key='CustomerKEY',
    attributes=['name', 'address'])

Part_Dimension = CachedDimension(
    name='Part_Dimension',
    key='PartKEY',
    attributes=['name', 'manufacturer'])

Date_Dimension = CachedDimension(
    name='Date_Dimension',
    key='DateKEY',
    attributes=['day', 'month', 'year'])

# Dimension roles
CommitDate_Dimension = Date_Dimension
ShippingDate_Dimension = Date_Dimension

Lineorder_Fact_Table = FactTable(
    name='Lineorder_Fact_Table',
    keyrefs=['CustomerKEY', 'PartKEY', 'CommitDate', 'ShippingDate'],
    measures=['quantity', 'price'])
